### ISSUE TITLE
recent python throws errors

### ISSUE THREAD

**Issue by teodorescuserban** [HXLStandard/hxl-proxy#104]
```
from hxl_proxy import app as application
>>> >>> >>> >>> /usr/lib/python3.5/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/www/hxl_proxy/__init__.py", line 34, in <module>
    import hxl_proxy.controllers
  File "/srv/www/hxl_proxy/controllers.py", line 46, in <module>
    app.register_error_handler(BaseException, error)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1186, in register_error_handler
    self._register_error_handler(None, code_or_exception, f)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 65, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1201, in _register_error_handler
    exc_class, code = self._get_exc_class_and_code(code_or_exception)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1125, in _get_exc_class_and_code
    assert issubclass(exc_class, Exception)
AssertionError
```

**Comment by danmihaila** [comment]
@davidmegginson any hint?

**Comment by teodorescuserban** [comment]
The new Flask 0.11.1 is responsible for those errors.

I have installed Flask 0.10.1 instead, all green.

@davidmegginson, please let me know what would the the short term solution and the long term one.

Should I make you a PR with a modified requirements.txt to make sure we use the right Flask until you can fix this in hxl proxy code?

Thank you!

**Comment by davidmegginson** [comment]
@teodorescuserban - you should be able to use Flask 0.11 now. It tests OK on my computer, but let me know if you see any problem (changes in the master branch).
