### ISSUE TITLE
Serialisation error for caching

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#260]
From @teodorescuserban :

I am trying to make cache request working. I get the following error on staging tools stack:

```
hxlproxy_1    | /usr/lib/python3.6/site-packages/flask_cache/jinja2ext.py:33: ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.
hxlproxy_1    |   from flask.ext.cache import make_template_fragment_key
hxlproxy_1    | Bad sheet index: None
hxlproxy_1    | Bad schema_sheet index: None
hxlproxy_1    | Exception possibly due to cache backend.
hxlproxy_1    | Traceback (most recent call last):
hxlproxy_1    |   File "/usr/lib/python3.6/site-packages/flask_cache/__init__.py", line 540, in decorated_function
hxlproxy_1    |     timeout=decorated_function.cache_timeout)
hxlproxy_1    |   File "/usr/lib/python3.6/site-packages/werkzeug/contrib/cache.py", line 824, in set
hxlproxy_1    |     pickle.dump(value, f, pickle.HIGHEST_PROTOCOL)
hxlproxy_1    | TypeError: cannot serialize '_io.TextIOWrapper' object
```
the config file is:

```
DEBUG=False
DB_FILE='/srv/db/hxl-proxy.db'
SECRET_KEY='<Something hard to guess>'
#
# File cache directory
#
CACHE_DIR = '/srv/cache/output/'
CACHE_MAX_ITEMS = 1000
CACHE_DEFAULT_TIMEOUT_SECONDS = 3600 # 1 hour

#
# Request cache
#
REQUEST_CACHE = '/srv/cache/hxl_proxy_requests'
REQUEST_CACHE_TIMEOUT_SECONDS = 3600
```

The cache folder is not being created (although the other cache folder, `/srv/cache/output` it is created and seems to work.

**Comment by davidmegginson** [comment]
From @danmihaila :+1: 
it is about the POST to https://feature-tools.humdata.org/hxlproxy/actions/validate when running https://feature-tools.humdata.org/wizard/#datacheck (the default example)

**Comment by davidmegginson** [comment]
The problem came from trying to serialise the _output_ of the hxl_proxy.util.run_validation function, which included an object with a file pointer. Refactored to avoid that.

**Comment by davidmegginson** [comment]
@danmihaila and @teodorescuserban : the fix is uploaded to the Git test branch and to https://beta.proxy.hxlstandard.org -- please test and confirm.
